<?php
/**
 * Shoping cart sidebar
 *
 * @see Web4Pro_AjaxAdding_Block_Cart_Sidebar
 */

?>

<?php
	$_cartQty = $this->helper('checkout/cart')->getSummaryCount(); 
    //$_cartQty = $this->getSummaryCount();
    if(empty($_cartQty)) {
        $_cartQty = 0;
    }
?>
<a href="#header-cart" class="skip-link skip-cart <?php if($_cartQty <= 0): ?> no-count<?php endif; ?>" >
    <span class="icon"></span>
    <span class="label">Cart</span>
    <span class="count"><?php echo $_cartQty; ?></span>
</a>

<div id="header-cart" class="block block-cart skip-content">
    <?php echo $this->getChildHtml('minicart_content');?>
</div>

